<a href="https://colab.research.google.com/github/asiddiqha/ML_Practice/blob/main/DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv('decision tree.csv')

In [4]:
df.head()

,Customer_ID,Age,Income,Student,Credit_Rating,Region,Online_Shopping,Previous_Purchases,Gender,Owns_Car,Buy_Laptop
0,C001,22,Low,Yes,Fair,South,Yes,1,Female,No,Yes
1,C002,25,Medium,Yes,Excellent,North,Yes,2,Male,No,Yes
2,C003,28,High,No,Fair,East,No,5,Male,Yes,No
3,C004,35,High,No,Excellent,West,No,8,Female,Yes,No
4,C005,30,Medium,Yes,Fair,South,Yes,4,Female,No,Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         30 non-null     object
 1   Age                 30 non-null     int64
 2   Income              30 non-null     object
 3   Student             30 non-null     object
 4   Credit_Rating       30 non-null     object
 5   Region              30 non-null     object
 6   Online_Shopping     30 non-null     object
 7   Previous_Purchases  30 non-null     int64
 8   Gender              30 non-null     object
 9   Owns_Car            30 non-null     object
 10  Buy_Laptop          30 non-null     object
dtypes: int64(2), object(9)
memory usage: 2.7+ KB

In [6]:
df.isnull().sum()

Customer_ID           0
Age                   0
Income                0
Student               0
Credit_Rating         0
Region                0
Online_Shopping       0
Previous_Purchases    0
Gender                0
Owns_Car              0
Buy_Laptop            0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
le = LabelEncoder()

for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = le.fit_transform(df[column])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         30 non-null     int64
 1   Age                 30 non-null     int64
 2   Income              30 non-null     int64
 3   Student             30 non-null     int64
 4   Credit_Rating       30 non-null     int64
 5   Region              30 non-null     int64
 6   Online_Shopping     30 non-null     int64
 7   Previous_Purchases  30 non-null     int64
 8   Gender              30 non-null     int64
 9   Owns_Car            30 non-null     int64
 10  Buy_Laptop          30 non-null     int64
dtypes: int64(11)
memory usage: 2.7 KB

In [10]:
df.head()

,Customer_ID,Age,Income,Student,Credit_Rating,Region,Online_Shopping,Previous_Purchases,Gender,Owns_Car,Buy_Laptop
0,0,22,1,1,1,2,1,1,0,0,1
1,1,25,2,1,0,1,1,2,1,0,1
2,2,28,0,0,1,0,0,5,1,1,0
3,3,35,0,0,0,3,0,8,0,1,0
4,4,30,2,1,1,2,1,4,0,0,1

In [11]:
X = df.drop('Buy_Laptop', axis=1)
y = df['Buy_Laptop']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
model = DecisionTreeClassifier(random_state = 42)
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)